import localFont from "next/font/local";
import { Manrope } from "next/font/google"; // Import the Google Font
import "./globals.css";

// Google Font
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"], // Include weights you need
  variable: "--font-manrope",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased bg-gray-200 text-gray-700 `}>
        {children}
      </body>
    </html>
  );
}
